[package]
name = "samp"
version = "0.1.0"
edition = "2021"

[dependencies]
zenoh = "1.0.0-beta.3"
tokio = { version = "1.40.0" , features = ["sync"]}
strum_macros = "0.26.4"
rand = "0.8.5"

[dev-dependencies]
clippy = "0.0.302"

